language: r
cache: packages

matrix:
  include:
    - r: devel
    - r: release
      after_success:
        - Rscript -e 'library(covr); codecov()'
    - r: oldrel

r_packages:
  - covr

before_install:
  - tlmgr install amsmath footmisc genmisc nowidow units
  - tlmgr install ly1 mathdesign utopia

addons:
  apt:
    packages:
      - ghostscript
